### ISSUE TITLE
スペックについて

### ISSUE THREAD

**Issue by sharo-jef** [japan-expert-force/auto-excavator#4]
スペックどする？

**Comment by sharo-jef** [comment]
確定ではないけど掘り方が変わるから広域ベースで幅優先or深さ優先で選択って感じか？

**Comment by Realitive-jef** [comment]
## 現在判明した問題点
- 現在の処理方式だと複数台設置した時、1Tickにおけるコマンドの実行可能上限数にすぐ到達するためマルチプレイ環境化において複数台稼働させられない。
     - 1Tickに実行できるコマンド数上限 
     `In Java Edition, the maximum number of scheduled ticks per game tick is 65,536.`
## メモ
- 採掘してる箇所を`Glowing`のエフェクトで表示すると採掘箇所を確認出来て便利

- ホッパーの上がフルブロックで塞がっているとホッパーが機能せずアイテムを回収できなくなる
    
## 所感
- 他のデータパックとも併用出来るようにするため、スペックを多少落としてでも1Tickのコマンド実行回数を減らして問題なく複数台(最大10台程度？)の運用出来るように採掘・処理方式を見直した方が良さそう

**Comment by Realitive-jef** [comment]
一応昨日Sharoと検証して分かった事を他の人も分かるように書いといた

**Comment by sharo-jef** [comment]
@Realitive-jef ty
