### ISSUE TITLE
アップグレードについて

### ISSUE THREAD

**Issue by sharo-jef** [japan-expert-force/auto-excavator#5]
アップグレードどする？

**Comment by sharo-jef** [comment]
## 方式案
### 1. マシン自体をアップグレード
例: Mekanismにおける `発展` -> `精鋭` みたいな感じ

#### 問題点
- アップグレード方法を考える必要がある
  - クラフトだとパターンが増えるたびに爆発的にレシピ数が増えそう
  - アイテムとして投げてマージする方法だとわかりづらい？

### 2. アップグレード用のアイテムを渡す
例: スピードアップグレードみたいなアイテムを渡す

#### 問題点
- 現状シングルブロックであるため渡し方を考える必要がある

## アップグレード内容案
- range
- speed
- silk touch
- fortune

**Comment by Realitive-jef** [comment]
## 方式案 2
### 現在のアップグレード状態の視覚化方法
1. `name_tag`のような表示機能を使って機械の上にアップグレード状況を視覚化する。
    - 多段階のアップグレードに対応しやすい
        - 例:`採掘速度上昇モジュール`を1個入れると`速度+5` 。追加で2個目入れたら `速度+10`みたいに表示される
        - 本体のコストを安くしてアップグレードモジュールのクラフトでバランスを取っていく場合によさそう
    - 多項目になった場合、視覚的に邪魔になる可能性あり

2. 本体の色（構成される素材）が変化する。
    - 複数種類のアップグレードを実装した場合パターンに対応できない
    - 外観から判断出来る

3. モジュール形式にしてUI上？に表示する。
     - アップグレードスロットを設けて特定のアイテムを入れると性能が変化する
     - 多段階のアップグレードには向かなそう

**Comment by Realitive-jef** [comment]
@sharo-jef 
本体をコスト安くしてアップグレードで機能性向上・バランスを取っていくいなら多段階アップグレードにしたいけど
モジュールを何らかの方法で本体に入れたとして多段階アップグレードって実装って可能なの？

**Comment by Realitive-jef** [comment]
![test](https://user-images.githubusercontent.com/82772868/118128115-71c60000-b435-11eb-963e-5b74459d52c8.png)

**Comment by sharo-jef** [comment]
> @sharo-jef
> 本体をコスト安くしてアップグレードで機能性向上・バランスを取っていくいなら多段階アップグレードにしたいけど
> モジュールを何らかの方法で本体に入れたとして多段階アップグレードって実装って可能なの？

可能か不可能かでは可能だろうけどだるい+ブロック増える気がする

**Comment by sharo-jef** [comment]
> ## 方式案 2
> ### アップグレード状態の視覚化方法
> 1. `name_tag`のような表示機能を使って機械の上にアップグレード状況を視覚化する。
>    
>    * 多段階のアップグレードに対応しやすい
>      
>      * 例:`採掘速度上昇モジュール`を1個入れると`速度+5` 。追加で2個目入れたら `速度+10`みたいに表示される
>      * 本体のコストを安くしてアップグレードモジュールのクラフトでバランスを取っていく場合によさそう
>    * 多項目になった場合、視覚的に邪魔になる可能性あり
> 2. 本体の色（構成される素材）が変化する。
>    
>    * 複数種類のアップグレードを実装した場合パターンに対応できない
>    * 外観から判断出来る
> 3. モジュール形式にしてUI上（インベントリスロット）に表示する。
>    
>    * アップグレードスロットを設けて特定のアイテムを入れると性能が変化する
>    * 多段階のアップグレードには向かなそう
>    * なんか工夫しないと実装大変そうだし見にくくなりそう

#2

**Comment by sharo-jef** [comment]
# 現状
採掘速度アップグレードは方式案の1を採用(機器自体をアップグレード)
シルクタッチ、幸運は方式案の2を採用(都度アイテムを入れる)

## 詳細
方式案2のアイテムにはディスクを使用
複数入れた際の処理をちゃんと書かないとアイテムを無駄に消費する可能性あり(既にアップグレード効果がついているのにまた消費される等)

**Comment by sharo-jef** [comment]
最高速で動かしているが十分遅いので速度アップグレードは見送り
方式案2のアップグレードは実装中
